before_commands:
    - "composer install --dev --prefer-source"

build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
        coverage:
            tests:
                override:
                    - command: composer test
                      coverage:
                          file: clover.xml
                          format: clover

checks:
    php: true

imports:
    - php
