imports:
  - php
checks:
    php: true
build:
  nodes:
    analysis:
      environment:
        php: 7.2
      dependencies:
        before:
          - composer update --dev --prefer-source
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run --standard=PSR2 ./src ./tests/AssetManagerTest
    coverage:
      tests:
        override:
          - command: composer test
            coverage:
              file: clover.xml
              format: clover
